services:
  server:
    build: ./server
    container_name: robo-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules
    restart: unless-stopped

  web:
    build: ./web
    container_name: robo-web
    ports:
      - "3001:80"
    restart: unless-stopped

volumes:
  server_node_modules:
